FROM php:8.1.31-fpm-alpine3.21

WORKDIR /home

RUN apk add --no-cache \
    wget \
    unzip \
    netcat-openbsd \
    curl \
    dcron \
    libpng-dev \
    zlib-dev \
    libjpeg-turbo-dev \
    openssl \
    libzip-dev \
    libpq-dev

RUN docker-php-ext-install \
    gd \
    zip \
    pdo_pgsql

RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer

RUN composer create-project wintercms/winter winter

RUN mv winter/ /var/www/html/

RUN chown -R www-data:www-data /var/www/html/winter/

WORKDIR /var/www/html/winter

COPY create_env.sh . 

RUN chmod +x create_env.sh && ./create_env.sh

COPY start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh

RUN php artisan key:generate && \
    php artisan config:clear && \
    php artisan cache:clear 

CMD ["/usr/local/bin/start.sh"]