apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx
  namespace: winter-dev
  labels:
    app: nginx
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/sites-available/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf

--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    server {
      listen 80;
      server_name _;
      root /var/www/winter/public;
      index index.php;

      location / {
          proxy_pass http://winter-php-service.winter-dev.svc.cluster.local:9000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
      }

      location ~ \.php$ {
        fastcgi_pass winter-php-service.winter-dev.svc.cluster.local:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_index index.php;
      }

      location /api/ {
        proxy_pass http://winter-php-service.winter-dev.svc.cluster.local:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      } 
    }

---
apiVersion: v1 
kind: Service 
metadata: 
  name: nginx-service
  labels:   
    app: nginx
spec:
  type: NodePort
  selector: 
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31052
