auth:
  postgresPassword: password
  username: mywinter
  password: password
  database: mywinter

readReplicas:
  replicaCount: 1

primary:
  persistence:
    existingClaim: pg-pvc
  pgHbaConfiguration: |-
    local all       postgres              peer
    local mywinter  mywinter              md5  
    host	mywinter	mywinter	0.0.0.0/0		md5
    
  configuration: |-
    listen_addresses = '*'