apiVersion: apps/v1
kind: Deployment 
metadata:
  name: winter-php
  labels:
    app: winter-php
  namespace: winter-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: winter-php
  template:
    metadata:
      labels:
        app: winter-php
    spec:
      containers:
        - name: winter-php 
          image: bakvivas/winter_cms:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_CONNECTION
              value: "pgsql"
            - name: DB_HOST
              value: "postgre-postgresql.winter-dev.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: mywinter
            - name: DB_USERNAME
              value: mywinter
            - name: DB_PASSWORD
              value: password
          volumeMounts:
            - name: php-fpm-config
              mountPath: /usr/local/etc/php-fpm.d/www.conf
              subPath: www.conf
            - name: php-fpm-log
              mountPath: /var/log
            - name: php-fpm-config
              mountPath: /usr/local/etc/php-fpm.conf
              subPath: php-fpm.conf
            # - name: php-fpm-config
            #   mountPath: /var/www/html/winter/.env
            #   subPath: .env
            #   readOnly: false
      volumes:
        - name: php-fpm-log
          emptyDir: {}
        - name: php-fpm-config
          configMap:
            name: php-fpm-config


---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: php-fpm-config
  namespace: winter-dev
data:
  www.conf: |
    [www]
    user = www-data
    group = www-data
    listen = 0.0.0.0:9000
    pm = dynamic
    pm.max_children = 5
    pm.start_servers = 2
    pm.min_spare_servers = 1
    pm.max_spare_servers = 3
  php-fpm.conf: |
    [global]
    include=etc/php-fpm.d/*.conf
  # .env: |
  #   APP_DEBUG=true
  #   APP_URL="http://localhost"
  #   APP_KEY="base64:7KFG1n07NW0unfPHTYSZWDAE41J0fzfWDnCyF2GleKA="

  #   DB_CONNECTION="pgsql"
  #   DB_HOST="postgre-postgresql.winter-dev.svc.cluster.local"
  #   DB_PORT=5432
  #   DB_DATABASE="mywinter"
  #   DB_USERNAME="mywinter"
  #   DB_PASSWORD="password"

  #   CACHE_DRIVER="file"

  #   SESSION_DRIVER="file"

  #   QUEUE_CONNECTION="sync"

  #   MAIL_MAILER="smtp"
  #   MAIL_ENCRYPTION="null"
  #   MAIL_HOST="smtp.mailgun.org"
  #   MAIL_PASSWORD="null"
  #   MAIL_PORT=587
  #   MAIL_USERNAME="null"

  #   ROUTES_CACHE=false
  #   ASSET_CACHE=false
  #   LINK_POLICY="detect"
  #   ENABLE_CSRF=true
  #   DATABASE_TEMPLATES=false

---
apiVersion: v1  
kind: Service 
metadata:
  name: winter-php-service
  namespace: winter-dev 
  labels: 
    app: winter-php 
spec: 
  selector: 
    app: winter-php 
  ports: 
    - protocol: TCP
      port: 9000
      targetPort: 9000